apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-redis-deployment
  labels:
    deployment: redis
spec:
  selector:
    matchLabels:
      pod: k8s-redis-pod
  replicas: 1
  template:
    metadata:
      labels:
        pod: k8s-redis-pod
    spec:
      containers:
        - name: k8s-redis-container
          image: redis
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 6379

