apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-django-deployment
  labels:
    app: k8s-django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-django-container
  template:
    metadata:
      labels:
        app: k8s-django-container
    spec:
      containers:
        - name: django-web
          image: raptivistos/k8s-django-minikube:1.0.5
          command: ['/bin/bash', 'run.sh'] # run migration and start the server
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: user

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password

            - name: POSTGRES_HOST
              value: postgres-service
