apiVersion: v1
kind: Service
metadata:
  name: k8s-django-service
spec:
  selector:
    app: k8s-django-container
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      # nodePort: 30001
  type: NodePort
