apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    pod: django
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      # nodePort: 30001
  type: NodePort
